server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    #druid配置
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/website?useUniCommonStatusEnum=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password:
      # 初始化大小，最小，最大
      initialSize:  1
      minIdle:  5
      maxActive:  20
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      maxWait:  6000
      timeBetweenEvictionRunsMillis:  60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery:  SELECT 1 FROM DUAL
      testWhileIdle:  true
      testOnBorrow:  false
      testOnReturn:  false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize:  20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters:  stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
mybatis:
  mapper-locations: com/potect/mapper/*.xml
  type-aliases-package: com.potect.pojo

  http:
    multipart:
      maxFileSize: 3Mb
      maxRequestSize: 3Mb